- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: diabled nodejs old and update new nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: install nodejs
    ansible.builtin.dnf:
    name: nodejs
    state: present
