- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: diabled nodejs old and update new nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: useradd nodejs
    ansible.builtin.user:
      name: roboshop

  - name: creae directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: downlaod application code to app diectory
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: unzip catalogue application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes