- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: diabled nodejs old and update new nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: useradd nodejs
    ansible.builtin.user:
      name: roboshop

  - name: creae directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: downlaod application code to app diectory
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: unzip catalogue application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: install depedensis
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: copy category services
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: deamon reloaded
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo
    
  - name: Install mongodb client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present

  - name: start & enable catalogue services
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes

  - name: get the category catalogue count
    ansible.builtin.command: mongo --host mongodb.jpdaws.cloud --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
    register: product_count

  - name: load catalogue data
    ansible.builtin.command: mongo --host mongodb.jpdaws.cloud < /app/schema/catalogue.js 
    when: product_count.stdout == "0"

  # - name: print the count
  #   ansible.builtin.debug:
  #     msg: "product count: {{product_count}}"

  # - name: load catalogue data
  #   ansible.builtin.command: mongo --host mongodb.jpdaws.cloud < /app/schema/catalogue.js
  #   when: product_count.stdout == "0" # keep double quotes

  - name: restart catalogue service
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes
