- main: mongodb 
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongodb repo
    ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo
    remote_src: yes
    
  - main: Install mongodb
    ansible.builtin.package:
    name: mongodb
    state: present
