- name: install payment component
  hosts: payments
  become: yes
  tasks: 
  - name: install paython 3.6
    ansible.builtin.dnf:
      name: "{{item}}"
      state: present
    loop:
      - python36 
      - gcc 
      - python3-devel

  -  name: user add
      ansible.builtin.user:
        name: roboshop

  - nmae: remove directory
    ansible.builtin.file:
      path: /app
      state: absent

- nmae: create directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download application
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/payments.zip
    dest: /tmp

- name: unzip application with app directory
  ansible.builtin.unarchive:
    src: /tmp/payments.zip
    dest: /app
    remote_src: yes

- name: Install dependencies
  ansible.builtin.command: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: Copy payment service
  ansible.builtin.copy:
    src: payment.service
    dest: /etc/systemd/system/payment.service

- name: deamon realod and start
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable payment
  ansible.builtin.service:
    name: payment
    state: restarted
    enabled: yes