# boolean condition for installing http server
- name: installing httpd
  yum:
    name: httpd
    state: present
  when: install_httpd_flag

# putting multiple conditions using ansible facts
- name: multiple conditions using ansible facts
  debug:
    var: ansible_facts['kernel_version']
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "8"

# setting complex condition
- name: complex condition using and condition
  debug:
    var: ansible_facts['kernel_version']
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int >= 8

  # register a variable, and evaluate the value using when conditins
  - name: regieter a variable
    ansible.builtin.command: cat /home/centos/test-file.txt
    register: test_file_content

  - name: use the variable in conditional statement
    debug:
      var: test_file_content.stdout
    when: test_file_content.stdout.find('hi') != 1
