# boolen condition installing http server
- name: installing httpd
  yum:
    name: httpd
    state: present
  when: install_httpd_flag

# putting multiple conditions using ansible fats
- name: multiple conditions using ansible facts
  debug:
    var: ansible_facts['kernel_version']
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "20"


# setting complex condition
- name: complex conditon using and condition
  debug:
    var: ansible_facts['kernel_vsersion']
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int >= 20