---

- name: install packages from python env
  become: yes
  yum:
    name:
      - python3-pip
    update_cache: yes

- name: create direactory
  file:
    path: ./basic-http-server
    state: directory

- name: install httpd
  become: yes
  yum:
    name: httpd
    update_cache: yes 
    state: latest